-- MySQL Script generated by MySQL Workbench
-- ven. 18 août 2017 17:29:03 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type` (
  `id` INT NOT NULL,
  `Label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `id` INT NOT NULL,
  `Label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Elements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Elements` (
  `id` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Date` DATE NULL,
  `Note` VARCHAR(45) NULL,
  `Description` MEDIUMTEXT NULL,
  `Image` VARCHAR(255) NULL,
  `Type_id` INT NOT NULL,
  `Genre_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Type_id`, `Genre_id`),
  INDEX `fk_Elements_Type1_idx` (`Type_id` ASC),
  INDEX `fk_Elements_Genre1_idx` (`Genre_id` ASC),
  CONSTRAINT `fk_Elements_Type1`
    FOREIGN KEY (`Type_id`)
    REFERENCES `mydb`.`Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Elements_Genre1`
    FOREIGN KEY (`Genre_id`)
    REFERENCES `mydb`.`Genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sex` (
  `id` INT NOT NULL,
  `Label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actors` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Date` VARCHAR(45) NOT NULL,
  `Sex_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Sex_id`),
  INDEX `fk_Actors_Sex1_idx` (`Sex_id` ASC),
  CONSTRAINT `fk_Actors_Sex1`
    FOREIGN KEY (`Sex_id`)
    REFERENCES `mydb`.`Sex` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Realisators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Realisators` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Date` VARCHAR(45) NOT NULL,
  `Sex_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Sex_id`),
  INDEX `fk_Realisators_Sex1_idx` (`Sex_id` ASC),
  CONSTRAINT `fk_Realisators_Sex1`
    FOREIGN KEY (`Sex_id`)
    REFERENCES `mydb`.`Sex` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Elements_has_Actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Elements_has_Actors` (
  `Elements_id` INT NOT NULL,
  `Actors_id` INT NOT NULL,
  PRIMARY KEY (`Elements_id`, `Actors_id`),
  INDEX `fk_Elements_has_Actors_Actors1_idx` (`Actors_id` ASC),
  INDEX `fk_Elements_has_Actors_Elements1_idx` (`Elements_id` ASC),
  CONSTRAINT `fk_Elements_has_Actors_Elements1`
    FOREIGN KEY (`Elements_id`)
    REFERENCES `mydb`.`Elements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Elements_has_Actors_Actors1`
    FOREIGN KEY (`Actors_id`)
    REFERENCES `mydb`.`Actors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Realisators_has_Elements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Realisators_has_Elements` (
  `Realisators_id` INT NOT NULL,
  `Elements_id` INT NOT NULL,
  PRIMARY KEY (`Realisators_id`, `Elements_id`),
  INDEX `fk_Realisators_has_Elements_Elements1_idx` (`Elements_id` ASC),
  INDEX `fk_Realisators_has_Elements_Realisators1_idx` (`Realisators_id` ASC),
  CONSTRAINT `fk_Realisators_has_Elements_Realisators1`
    FOREIGN KEY (`Realisators_id`)
    REFERENCES `mydb`.`Realisators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Realisators_has_Elements_Elements1`
    FOREIGN KEY (`Elements_id`)
    REFERENCES `mydb`.`Elements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
